### ISSUE TITLE
One_hot feature

### ISSUE THREAD

**Issue by shaswat01** [dsi-principles-prog/midterm-shaswat01#1]
for ML model it's btter to have the predicted column to be a integer than string. In this dataset we are predicting whether the type of cancer is Benign or Malignant. So the user have make change in this column to make a new column called Diagnosis, so that it shows 1 for benign and 2 for malignant.
Output should be either 1 or 2.

Sample output - 
<img width="96" alt="Screenshot 2019-10-28 at 11 14 09 AM" src="https://user-images.githubusercontent.com/26230787/67696005-137d1d80-f974-11e9-8793-b7d9906825c9.png">

**Comment by aliforgetti** [comment]
added one hot encoding feature!
